apiVersion: v1
kind: Service
metadata:
  name: front
  labels:
    app: front
spec:
  type: NodePort
  selector:
    app: front
  ports:
    - name: http
      port: 80
      nodePort: 31009
      targetPort: 80